theme: jekyll-theme-minimal
title: José Orlando Pereira
logo: photo.jpg
description: "&#9993; <a href=\"mailto:jop@di.uminho.pt\">jop@di.uminho.pt</a></br>&#9743; <a href=\"tel:+351253604449\">+351 253604449</a>"
show_downloads: false